quotes/urls.py
from django.urls import path
from .views import home,about,add_stock,delStock,delete_stock

app_name = 'quotes'

urlpatterns = [
    path('',home,name='home'),
    path('about/',about,name='about'),
    path('add-stock/',add_stock,name='add_stock'),
    path('delete/<int:pk>',delStock, name='del_stock'),
    path('delete_stock',delete_stock,name='delete_stock'),

]

stocks/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('quotes.urls')),
]

quotes/models.py
from django.db import models


class Stock(models.Model):
    ticker = models.CharField(max_length=10)

    def __str__(self):
        return self.ticker

quotes/forms.py
from django.forms import models
from .models import Stock


class StockForm(models.ModelForm):
    class Meta:
        model = Stock
        fields = ['ticker']

quotes/views.py
from django.shortcuts import render, redirect
from .models import Stock
from .forms import StockForm
from django.contrib import messages


def home(request):
    if request.method == 'POST':
        ticker = request.POST['ticker_symbol']
        import requests
        import json
        api_request = requests.get(
            "https://cloud.iexapis.com/stable/stock/" + ticker + "/quote?token=pk_3e3c4cff7a7c4df684e55115360ea253")
        try:
            api = json.loads(api_request.content)
        except Exception as e:
            api = "It doesn't work...."

        return render(request, 'quotes/home.html', {"api": api})
    else:
        return render(request, 'quotes/home.html', {"ticker": "Enter a Ticker Symbole Above..."})


def about(request):
    return render(request, 'quotes/about.html')


def add_stock(request):
    import requests
    import json
    ticker = Stock.objects.all()
    api_items = []
    for ticker_item in ticker:
        api_request = requests.get(
            "https://cloud.iexapis.com/stable/stock/" + str(
                ticker_item) + "/quote?token=pk_3e3c4cff7a7c4df684e55115360ea253")
        try:
            api = json.loads(api_request.content)
            api_items.append(api)
        except Exception as e:
            api = "It doesn't work...."
    if request.method == 'POST':
        form = StockForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Stock has been added successfully')
            return redirect('quotes:add_stock')
    else:
        form = StockForm()
    tt = {
        "ticker": ticker,
        "form": form,
        "api": api_items
    }

    return render(request, 'quotes/add_stock.html', tt)


def delStock(request, pk):
    item = Stock.objects.get(pk=pk)
    item.delete()
    messages.success(request, 'Stock Has been Delete')
    return redirect('quotes:delete_stock')


def delete_stock(request):
    ticker = Stock.objects.all()
    return render(request, 'quotes/delete_stock.html',{'ticker':ticker})

quotes/templates/quotes/about.html
{% extends 'quotes/base.html'%}
{% block content %}
<h1>About Page</h1>
{% endblock content%}

quotes/templates/quotes/add_stock.html
{% extends 'quotes/base.html'%}
{% block content %}
<h1>Add Stock Page</h1>


<form action="{% url 'quotes:add_stock' %}" method="post" class="d-flex">
    {% csrf_token %}
    {{ form }}
    <button class="btn btn-outline-success" type="submit"> Add</button>
</form>


<table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Company Name</th>

        <th scope="col">Price</th>
        <th scope="col">Previous Close</th>
        <th scope="col">Market Cap</th>
        <th scope="col">YTD Change</th>
        <th scope="col">52WK High</th>
        <th scope="col">52WK Low</th>
    </tr>
    </thead>
    <tbody>
    {% if ticker %}


    {% for i in api %}
    <tr>
        <th scope="row">{{i.companyName}}</th>
        <td>${{ i.latestPrice }}</td>
        <td>${{ i.previousClose }}</td>
        <td> ${{ i.marketCap }}</td>
        <td>{{i.ytdChange }}</td>
        <td>${{i.week52High }}</td>
        <td>${{i.week52Low }}</td>

    </tr>
    {% endfor %}


    {% endif %}
    </tbody>
</table>


{% endblock content%}

quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Hello, world!</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'quotes:home' %}">Stock</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'quotes:about' %}">About</a>
                </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'quotes:add_stock' %}">Add Stock</a>
                </li>
                    <li class="nav-item">
                    <a class="nav-link" href="{% url 'quotes:delete_stock' %}">Delete Stock</a>
                </li>
            </ul>
            <form action="{% url 'quotes:home' %}"  method="post" class="d-flex">
                {% csrf_token %}
                <input class="form-control me-2" type="search" placeholder="Get Stock quote" aria-label="Search" name="ticker_symbol">
                <button class="btn btn-outline-success" type="submit">Stock</button>
            </form>
        </div>
    </div>
</nav>



{% if messages %}
 {% for message in messages %}
<div class="alert alert-success alert-dismissible fade show" role="alert">
  {{message}}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>

</div>
{% endfor %}
{% endif%}

{% block content %}

{% endblock content%}

<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
-->
</body>
</html>

quotes/templates/quotes/delete_stock.html
{% extends 'quotes/base.html'%}
{% block content %}
<h1>Delete Page</h1>
{% if ticker %}
{% for tick in ticker %}
{{ tick }} <a href="{% url 'quotes:del_stock' tick.id %}">Delete</a><br>
{% endfor %}
{% else %}
<p>You don't have any stocks</p>
{% endif %}
{% endblock content%}

quotes/templates/quotes/home.html
{% extends 'quotes/base.html'%}
{% block content %}
<h1>Home Page</h1>
<br>
<br>
{% if ticker %}
{{ticker}}
{% endif %}


{% if api %}
{% if api == "It doesn't work...." %}
There was a problem with your ticker symbol, please try again...
{% else %}
<h1>{{ api.companyName }}</h1> <br>
 <br>
Price: ${{ api.latestPrice }} <br>
Previous Close: {{ api.previousClose }} <br>
Market Cap: {{ api.marketCap }} <br>
YTD Change: {{api.ytdChange }} <br>
52WK High:  {{api.week52High }} <br>
52WK Low:  {{api.week52Low }} <br>
{{ api. }} <br>


{% endif %}
{% endif %}

{% endblock content%}